FROM debian:bullseye

RUN apt-get update && apt-get install -y build-essential curl meson
RUN curl -LO https://github.com/Pro/raspi-toolchain/releases/download/v1.0.2/raspi-toolchain.tar.gz && \
    tar xfz raspi-toolchain.tar.gz --strip-components=1 -C /opt && rm raspi-toolchain.tar.gz
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
RUN /root/.cargo/bin/rustup target add arm-unknown-linux-gnueabihf

ENV PATH=/opt/cross-pi-gcc/bin/:$PATH
